### ISSUE TITLE
using radium with react package

### ISSUE THREAD

**Issue by markshust** [ccorcos/meteor-react-radium#1]
Would like to use radium, however I'm using the official `react` package provided by meteor. I installed this package and it works good, but it appears to load two react.js files and not set displayName. How can one go about installing radium with `react` package compatibility?

**Comment by ccorcos** [comment]
not sure... ive since ditched radium :/

**Comment by markshust** [comment]
Can I ask what you are using? Open to alternatives... :)

**Comment by ccorcos** [comment]
I'm using stylus actually. It has a lot of functionality. Functions. Mixins. Etc. I really like it. I wish I could do everything in coffeescript but that's just not possible at the moment. It would be cool if react would allow you to tie inline styles to elements using class selectors, etc.

**Comment by markshust** [comment]
oh you are one of those :imp: 

hah just kidding... love coffeescript and didn't know about stylus. very neat. i'm kinda going back to full javascript right now because of jsx. bummer but thats how she goes, just need the consistency throughout the app.

anyways, i see inline style format as being great so wanted to get this to work. if anyone wants to know i got radium working straight up with `meteorhacks:npm`. there is a bug in the react-in-meteor documentation i found (https://github.com/meteor/react-packages/issues/94), updated this and all started working with meteor-provided `react` package.

**Comment by ccorcos** [comment]
cool cool. I'm a big fan of coffescript honestly. js and jsx require too much typing for my taste ;)

**Comment by ccorcos** [comment]
For example, here's how I do react with coffeescript. This is a list that renders a bunch of items along with loading and a load more button. I think its really elegant -- much better than using JSX. the `cond` function is clutch too -- it s will call the first function or the second function based on the truthy-ness of the first argument

``` coffee
    div
      className: ['list col', @props.className].join(' ')
      @props.items?.map(@props.renderItem)
      cond @props.loading,
        => div
          className: 'load-more'
          Spinner()
        => cond @props.loadMore,
          => div
            className: 'load-more'
            onClick: debounce(@props.loadMore)
            'LOAD MORE'
          => cond @props.items?.length is 0,
            => div
              className: 'empty-list'
              'No results'
```

**Comment by markshust** [comment]
thanks for the info -- that is neat

**Comment by markshust** [comment]
FYI also switching off of radium. I like the idea but in practice it slows down development quite a bit. Didn't know about all of the acceptable formats for stylus... pretty sure I'm moving there also.

**Comment by ccorcos** [comment]
yeah. and its hard to separate all your code. every element needs this style object which gets a little challenging... but yeah, check out stylus. 

This is where I was immediately sold on stylus: Stylus has a ton of programming functionality -- its almost like coffeescript. I made these functions to build animations for react's CSSTransitionGroup. Fore example:

``` styl
animate-fade-in(name, action)
  .{name}-{action}
    opacity: 0

  .{name}-{action}.{name}-{action}-active
    transition: opacity .2s ease
    opacity: 1

animate-fade-out(name, action)
  .{name}-{action}
    opacity: 1

  .{name}-{action}.{name}-{action}-active
    transition: opacity .2s ease
    opacity: 0

animate-fade(name)
  animate-fade-in(name, 'appear')
  animate-fade-in(name, 'enter')
  animate-fade-out(name, 'leave')
```

And I'm using rupture for some convenient mixing for responsiveness, and then in my `main.styl` file, after I import the animations file, I can specify all the animations in my app like this:

``` styl
animate-slide-up('small-tabbar-transition')
animate-fade('large-tabbar-transition')
animate-fade('login-error')
animate-fade('login-loading')
animate-fade('content-transition')
animate-fade('tabvc')
+above(break)
  animate-fade('navvc-push')
  animate-fade('navvc-pop')
+below(break)
  animate-push('navvc-push')
  animate-pop('navvc-pop')
+above(break)
  animate-delay-fade('nav-left')
  animate-delay-fade('nav-right')
+below(break)
  animate-scale('nav-left')
  animate-scale('nav-right')
animate-fade('nav-title')
```

For example, on larger screen navigation push and pop animations are just a fade, but on smaller screens they're a slide left and slide right. But its super easy to change any animations just by changing a single line of stylus :)
